"""empty message

Revision ID: 882c17b12342
Revises: 
Create Date: 2019-11-06 16:03:34.830503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '882c17b12342'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('realurl', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_table('record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('detail', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('ip', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_table('record_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=11), nullable=True),
    sa.Column('mail', sa.String(length=255), nullable=True),
    sa.Column('image1', sa.Integer(), nullable=True),
    sa.Column('image2', sa.Integer(), nullable=True),
    sa.Column('image3', sa.Integer(), nullable=True),
    sa.Column('image4', sa.Integer(), nullable=True),
    sa.Column('image5', sa.Integer(), nullable=True),
    sa.Column('image6', sa.Integer(), nullable=True),
    sa.Column('image7', sa.Integer(), nullable=True),
    sa.Column('image8', sa.Integer(), nullable=True),
    sa.Column('image9', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('record_detail')
    op.drop_table('record')
    op.drop_table('image')
    # ### end Alembic commands ###
